name: Auto Push Changes

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto-pushed changes" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
